home_page:
    pattern:  /
    defaults: { _controller: PowerGridBundle:Default:index }

status:
    pattern:  /status
    defaults: { _controller: PowerGridBundle:Default:status }

history:
    pattern:  /history
    defaults: { _controller: PowerGridBundle:Default:history }


history_archive_month_and_year:
    pattern: /history/{year}/{month}
    defaults: { _controller: PowerGridBundle:Default:history }

history_day_tsv:
    pattern: /history/tsv/{year}/{month}/{day}
    defaults: { _controller: PowerGridBundle:Default:historytsv }

history_archive_month_and_year_tsv:
    pattern: /history/tsv/{year}/{month}
    defaults: { _controller: PowerGridBundle:Default:historytsv }

api:
    pattern: /api
    defaults: { _controller: PowerGridBundle:Default:api}

about:
    pattern: /about
    defaults: { _controller: PowerGridBundle:Default:about}

contact:
    pattern: /contact
    defaults: { _controller: PowerGridBundle:Default:contact}

faq:
    pattern: /faq
    defaults: { _controller: PowerGridBundle:Default:faq}

# power_grid:
    # resource: "@PowerGridBundle/Resources/config/routing.yml"
    # prefix:   /
#
